In [83]:
from pandas_datareader import data
import datetime
from bokeh.plotting import figure, show, output_file

In [137]:
start = datetime.datetime(2021,1,1)
end = datetime.datetime(2022,1,1)

df=data.DataReader(name="FB",data_source="yahoo", start=start, end=end) 
df

,High,Low,Open,Close,Volume,Adj Close
Date,,,,,,
2021-01-04,275.000000,265.200012,274.779999,268.940002,15106100,268.940002
2021-01-05,272.399994,268.209991,268.290009,270.970001,9871600,270.970001
2021-01-06,267.750000,260.010010,262.000000,263.309998,24354100,263.309998
2021-01-07,271.609985,264.779999,265.899994,268.739990,15789800,268.739990
2021-01-08,268.950012,263.179993,268.309998,267.570007,18528300,267.570007
...,...,...,...,...,...,...
2021-12-27,347.869995,338.010010,338.850006,346.179993,17795000,346.179993
2021-12-28,352.709991,345.200012,346.630005,346.220001,16637600,346.220001
2021-12-29,349.690002,341.640015,346.910004,342.940002,10747000,342.940002
2021-12-30,347.230011,343.220001,344.000000,344.359985,10593300,344.359985
2021-12-31,343.440002,336.269989,343.019989,336.350006,12870500,336.350006

In [138]:
# data.DataReader?

In [139]:
# df.index

In [140]:
# df["Open"]

In [141]:
# df.Open

In [142]:
# df.index[df.Close > df.Open] #list of days when close is greater than open

In [143]:
#you can use these variables instead of typing it directly
date_increase = df.index[df.Close > df.Open]
date_decrease= df.index[df.Close < df.Open]

In [144]:
#we made a fn that takes values of close and open 
#it prints increase when close is >, decrease when Open is < or =
def inc_dec(c, o):
    if c > o:
        value = "Increase"
    elif c < o:
        value = "Decrease"
    else:
        value="Equal"
    return value

#we are creating a new column, status but through iteration
#for each of the values in colum close and open pass those values to our fn
df["Status"]=[inc_dec(c, o) for c, o in zip(df.Close, df.Open)]

In [145]:
df["Middle"] = (df.Open + df.Close)/2
df["Height"] = abs(df.Close - df.Open)
df

,High,Low,Open,Close,Volume,Adj Close,Status,Middle,Height
Date,,,,,,,,,
2021-01-04,275.000000,265.200012,274.779999,268.940002,15106100,268.940002,Decrease,271.860001,5.839996
2021-01-05,272.399994,268.209991,268.290009,270.970001,9871600,270.970001,Increase,269.630005,2.679993
2021-01-06,267.750000,260.010010,262.000000,263.309998,24354100,263.309998,Increase,262.654999,1.309998
2021-01-07,271.609985,264.779999,265.899994,268.739990,15789800,268.739990,Increase,267.319992,2.839996
2021-01-08,268.950012,263.179993,268.309998,267.570007,18528300,267.570007,Decrease,267.940002,0.739990
...,...,...,...,...,...,...,...,...,...
2021-12-27,347.869995,338.010010,338.850006,346.179993,17795000,346.179993,Increase,342.514999,7.329987
2021-12-28,352.709991,345.200012,346.630005,346.220001,16637600,346.220001,Decrease,346.425003,0.410004
2021-12-29,349.690002,341.640015,346.910004,342.940002,10747000,342.940002,Decrease,344.925003,3.970001
2021-12-30,347.230011,343.220001,344.000000,344.359985,10593300,344.359985,Increase,344.179993,0.359985
2021-12-31,343.440002,336.269989,343.019989,336.350006,12870500,336.350006,Decrease,339.684998,6.669983

In [151]:
# df.Status=="Increase"
# df.Status=="Decrease"
# p.rect?
# p.segment?
# figure?
p?

In [147]:
p=figure(x_axis_type='datetime', width=1000, height=300,)
p.title="Candlestick Chart"
p.grid.grid_line_alpha=0.3 #controlling grid

##x0 = date,  y0 = df.High 
##x1 = date, y1 = df.low
##segment first so as to allow rect to come in front
p.segment(df.index, df.High, df.index, df.Low, color='black') 

hours_12 = 12*60*60*1000

##hardcodding the statement
# p.quad(df.index[df.Close > df.Open], (df.Open + df.Close)/2,
#        hours_12, abs(df.Open-df.Close), fill_color="green", line_color="black")

# p.quad(df.index[df.Close < df.Open], (df.Open + df.Close)/2,
#        hours_12, abs(df.Open-df.Close), fill_color="green", line_color="black")

##using variables to hold the diff of the values of the close and open cell
# p.quad(date_increase, (df.Open + df.Close)/2,
#        hours_12, abs(df.Open-df.Close), fill_color="green", line_color="black")

# p.quad(date_decrease, (df.Open + df.Close)/2,
#        hours_12, abs(df.Open-df.Close), fill_color="green", line_color="black")

##for when Close > Open the first instance will apply else the second does
##x is datetime object of open or close
##y is value of open and close on a particular date
##width is a point on y, where close and open values averages which was used as width
##height is the difference on y, values of open and close that's is a difference of open and close 
p.rect(df.index[df.Status=="Increase"], df.Middle[df.Status=="Increase"],
       hours_12, df.Height[df.Status=='Increase'], fill_color="#ff4000", line_color="black")

p.rect(df.index[df.Status=="Decrease"], df.Middle[df.Status=="Decrease"],
       hours_12, df.Height[df.Status=='Decrease'], fill_color="#00ff00", line_color="black")

output_file("cs.html")
show(p)

In [154]:
# import pandas_datareader as pdr
# pdr.get_data_fred('GS10') #THIS TOO WORKS
figure?